// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using Foundation;
using UIKit;
using FPT.Framework.iOS.UI.PagerTabStrip;

namespace Demo
{
	public partial class BarExampleViewController : ButtonBarPagerTabStripViewController
	{

		#region PROPERTIES

		bool IsReload { get; set; } = false;

		#endregion

		#region CONSTRUCTORS

		public BarExampleViewController (IntPtr handle) : base (handle)
		{
		}

		public BarExampleViewController(NSCoder coder) : base(coder)
		{
		}

		#endregion


		#region FUNCTIONS

		public override void ViewDidLoad()
		{

			Settings.Style.SelectedBarBackgroundColor = UIColor.Orange;

			base.ViewDidLoad();
		}

		public override IList<UIViewController> GetViewControllers(PagerTabStripViewController pagerTabStripController)
		{
			var child_1 = new TableChildExampleViewController(UITableViewStyle.Plain, new IndicatorInfo("TableView"));
			var child_2 = new ChildExampleViewController(new IndicatorInfo("View"));
			var child_3 = new TableChildExampleViewController(UITableViewStyle.Grouped, new IndicatorInfo("Table View 2"));
			var child_4 = new ChildExampleViewController(new IndicatorInfo("View 2"));
			var child_5 = new TableChildExampleViewController(UITableViewStyle.Plain, new IndicatorInfo("TableView 3"));
			var child_6 = new ChildExampleViewController(new IndicatorInfo("View 3"));
			var child_7 = new TableChildExampleViewController(UITableViewStyle.Grouped, new IndicatorInfo("Table View 4"));
			var child_8 = new ChildExampleViewController(new IndicatorInfo("View 4"));

			var childViewControllers = new List<UIViewController>()
			{
				child_1, child_2, child_3, child_4, child_5, child_6, child_7, child_8
			};

			if (!IsReload)
			{
				return childViewControllers;
			}

			for (var index = 0; index < childViewControllers.Count; index++)
			{
				var nElements = childViewControllers.Count - index;
				var n = (new Random()).Next(nElements) + index;
				if (n != index)
				{
					Swap(childViewControllers, index, n);
				}
			}
			var nItems = 1 + (new Random()).Next(8);
			return childViewControllers.Take(nItems).ToList();
		}

		public override void ReloadPagerTabStripView()
		{
			IsReload = true;
			if ((new Random()).Next(2) == 0)
			{
				PagerBehaviour = PagerTabStripBehaviour.Progressive((new Random()).Next(2) == 0, (new Random()).Next(2) == 0);
			}
			else
			{
				PagerBehaviour = PagerTabStripBehaviour.Common((new Random()).Next(2) == 0);
			}
			base.ReloadPagerTabStripView();
		}

		#endregion

		#region HELPERS

		static void Swap(IList<UIViewController> list, int indexA, int indexB)
		{
			var tmp = list[indexA];
			list[indexA] = list[indexB];
			list[indexB] = tmp;
		}

		#endregion
	}
}
