// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using FPT.Framework.iOS.UI.PagerTabStrip;

namespace Demo
{
	public partial class ButtonBarExampleViewController : ButtonBarPagerTabStripViewController
	{
		public ButtonBarExampleViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
