// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using Foundation;
using UIKit;
using FPT.Framework.iOS.UI.PagerTabStrip;

namespace Demo
{
	public partial class ReloadExampleViewController : UIViewController
	{
		public ReloadExampleViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			if (NavigationController != null)
			{
				
			}

			var pagerViewController = ChildViewControllers.Where(_ => _ is PagerTabStripViewController).FirstOrDefault();
			if (pagerViewController != null)
			{
				updateTitle(pagerViewController as PagerTabStripViewController);
			}
		}

		void updateTitle(PagerTabStripViewController pagerTabStripViewController)
		{
			titleLabel.Text = string.Format("Progressive = {0}  ElasticLimit = {1}",
			                                pagerTabStripViewController.PagerBehaviour.ProgressiveIndicator.ToString(),
			                                pagerTabStripViewController.PagerBehaviour.ElasticIndicatorLimit.ToString());
		}

		public override UIStatusBarStyle PreferredStatusBarStyle()
		{
			return UIStatusBarStyle.LightContent;
		}
	}
}
